
services:
  # Eureka Server (Service Discovery)
  eureka-server:
    build:
      context: ./eureka-server  # Directory containing the Dockerfile.keycloak
    ports:
      - "${EUREKA_PORT}:8761"  # Eureka dashboard
    environment:
      - SPRING_PROFILES_ACTIVE=${ACTIVE_PROFILE}
      - TZ=${TIMEZONE}
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
#      interval: 30s
#      timeout: 10s
#      retries: 5

  # Config Server (Spring Cloud Config)
  config-service:
    build:
      context: ./config-service
    ports:
      - "${CONFIG_PORT}:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=${ACTIVE_PROFILE}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_URL}
      - TZ=${TIMEZONE}
    depends_on:
      - eureka-server
    volumes:
      - ./config-repo:/config-repo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "${API_GATEWAY_PORT}:8080"
    environment:
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KC_REALM=${KC_REALM}
      - KC_CLIENT_ID=${KC_CLIENT_ID}
      - KC_CLIENT_SECRET=${KC_CLIENT_SECRET}
      - KC_USERNAME=${KC_USERNAME}
      - KC_PASSWORD=${KC_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${ACTIVE_PROFILE}
      - CLOUD_CONFIG_URL=${CLOUD_CONFIG_URL}
      - SPRING_CLOUD_CONFIG_URI=${CLOUD_CONFIG_URL}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_URL}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=${JWT_ISSUER_URI}
      - TZ=${TIMEZONE}
    depends_on:
      keycloak:
        condition: service_healthy
      config-service:
        condition: service_healthy
      eureka-server:
        condition: service_started

  # Auth Service
  auth-service:
    build:
      context: ./auth-service
    ports:
      - "${AUTH_PORT}:8081"
    environment:
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KC_REALM=${KC_REALM}
      - KC_CLIENT_ID=${KC_CLIENT_ID}
      - KC_CLIENT_SECRET=${KC_CLIENT_SECRET}
      - KC_USERNAME=${KC_USERNAME}
      - KC_PASSWORD=${KC_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${ACTIVE_PROFILE}
      - CLOUD_CONFIG_URL=${CLOUD_CONFIG_URL}
      - SPRING_CLOUD_CONFIG_URI=${CLOUD_CONFIG_URL}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_URL}
      - TZ=${TIMEZONE}
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/auth_database
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      keycloak:
        condition: service_healthy
      config-service:
        condition: service_started
      eureka-server:
        condition: service_started
      postgres:
        condition: service_started

  employee-service:
    build:
      context: ./employee-service
    ports:
      - "${EMPLOYEE_PORT}:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=${ACTIVE_PROFILE}
      - CLOUD_CONFIG_URL=${CLOUD_CONFIG_URL}
      - SPRING_CLOUD_CONFIG_URI=${CLOUD_CONFIG_URL}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_URL}
      - SPRING_DATASOURCE_URL=${DB_URL}/employee_database
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - TZ=${TIMEZONE}
    depends_on:
      keycloak:
        condition: service_healthy
      config-service:
        condition: service_healthy
      eureka-server:
        condition: service_started
      postgres:
        condition: service_started


  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

  # Keycloak (Identity Provider)
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile.keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=${DB_URL}/keycloak
      - KC_DB_USERNAME=${DB_USER}
      - KC_DB_PASSWORD=${DB_PASSWORD}
      - KC_HTTP_ENABLED=true
      - TZ=${TIMEZONE}
    ports:
      - "8180:8080"
    command: ["start","--import-realm","--verbose","--hostname=https://auth.renzoproject.site","--proxy-headers=xforwarded"]
    volumes:
      - ./config:/opt/keycloak/data/import
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/realms/master" ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 90s
    depends_on:
      - postgres

volumes:
  postgres_data:
  config-repo: