spring:
  application:
    name: api-gateway
  profiles:
    active: dev
  config:
    import: optional:configserver:${CLOUD_CONFIG_URL:http://localhost:8888/}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
management:
  endpoints:
    web:
      exposure:
        include: "*"
