spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:https://microservice-project-347v.onrender.com/

management:
  endpoints:
    web:
      exposure:
        include: "*"
