spring:
  application:
    name: employee-service
  config:
    import: optional:configserver:http://config-service:8888/
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
