spring:
  application:
    name: employee-service
  profiles:
    active: dev
  config:
    import: optional:configserver:${CLOUD_CONFIG_URL:http://localhost:8888/}
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
