spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rnzmndz/config.git
#          search-paths: config // use this when you use the link of microservice-component
          default-label: main
          clone-on-start: true

server:
  port: 8888

logging:
  level:
    root: DEBUG